TEST_ROOT_TABLES = {
    'tenders': ['/tender'],
    'awards': ['/awards'],
    'contracts': ['/contracts'],
    'planning': ['/planning'],
    'parties': ['/parties']
}
TEST_COMBINED_TABLES = {
    # 'documents': [
    #     '/planning/*/documents',
    #     '/tender/*/documents',
    #     '/awards/*/documents',
    #     '/contracts/*/documents',
    # ],
    # 'milestones': [
    #     '/planning/milestones',
    #     '/tender/milestones',
    #     '/contracts/milestones',
    #     '/contracts/implementation/milestones'
    # ],
    # 'amendments': [
    #     "/planning/milestones",
    #     "/tender/milestones",
    #     "/contracts/milestones",
    #     "/contracts/implementation/milestones"
    # ]
}



tenders_columns = [
    '/ocid',
    '/tender/id',
    '/tender/title',
    '/tender/description',
    '/tender/status',
    '/tender/procurementMethod',
    '/tender/procurementMethodDetails',
    '/tender/procurementMethodRationale',
    '/tender/mainProcurementCategory',
    '/tender/awardCriteria',
    '/tender/awardCriteriaDetails',
    '/tender/submissionMethodDetails',
    '/tender/hasEnquiries',
    '/tender/eligibilityCriteria',
    '/tender/numberOfTenderers',
    '/tender/contractPeriod/startDate',
    '/tender/contractPeriod/endDate',
    '/tender/contractPeriod/maxExtentDate',
    '/tender/contractPeriod/durationInDays',
    '/tender/awardPeriod/startDate',
    '/tender/awardPeriod/endDate',
    '/tender/awardPeriod/maxExtentDate',
    '/tender/awardPeriod/durationInDays',
    '/tender/enquiryPeriod/startDate',
    '/tender/enquiryPeriod/endDate',
    '/tender/enquiryPeriod/maxExtentDate',
    '/tender/enquiryPeriod/durationInDays',
    '/tender/tenderPeriod/startDate',
    '/tender/tenderPeriod/endDate',
    '/tender/tenderPeriod/maxExtentDate',
    '/tender/tenderPeriod/durationInDays',
    '/tender/minValue/amount',
    '/tender/minValue/currency',
    '/tender/value/amount',
    '/tender/value/currency',
    '/tender/procuringEntity/name',
    '/tender/procuringEntity/id'
]
tenders_arrays = [
    '/tender/items',
    '/tender/additionalProcurementCategories',
    '/tender/submissionMethod',
    '/tender/tenderers',
    '/tender/documents',
    '/tender/milestones',
    '/tender/amendments',
    '/tender/items/additionalClassifications'
]
tenders_combined_columns = [
    '/ocid',
    '/tender/id',
    '/tender/title',
    '/tender/description',
    '/tender/status',
    '/tender/procurementMethod',
    '/tender/procurementMethodDetails',
    '/tender/procurementMethodRationale',
    '/tender/mainProcurementCategory',
    '/tender/additionalProcurementCategories/0',
    '/tender/awardCriteria',
    '/tender/awardCriteriaDetails',
    '/tender/submissionMethod/0',
    '/tender/submissionMethod/0Details',
    '/tender/hasEnquiries',
    '/tender/eligibilityCriteria',
    '/tender/numberOfTenderers',
    '/tender/amendments/0/date',
    '/tender/amendments/0/rationale',
    '/tender/amendments/0/id',
    '/tender/amendments/0/description',
    '/tender/amendments/0/amendsReleaseID',
    '/tender/amendments/0/releaseID',
    '/tender/milestones/0/id',
    '/tender/milestones/0/title',
    '/tender/milestones/0/type',
    '/tender/milestones/0/description',
    '/tender/milestones/0/code',
    '/tender/milestones/0/dueDate',
    '/tender/milestones/0/dateMet',
    '/tender/milestones/0/dateModified',
    '/tender/milestones/0/status',
    '/tender/documents/0/id',
    '/tender/documents/0/documentType',
    '/tender/documents/0/title',
    '/tender/documents/0/description',
    '/tender/documents/0/url',
    '/tender/documents/0/datePublished',
    '/tender/documents/0/dateModified',
    '/tender/documents/0/format',
    '/tender/documents/0/language',
    '/tender/tenderers/0/name',
    '/tender/tenderers/0/id',
    '/tender/contractPeriod/startDate',
    '/tender/contractPeriod/endDate',
    '/tender/contractPeriod/maxExtentDate',
    '/tender/contractPeriod/durationInDays',
    '/tender/awardPeriod/startDate',
    '/tender/awardPeriod/endDate',
    '/tender/awardPeriod/maxExtentDate',
    '/tender/awardPeriod/durationInDays',
    '/tender/enquiryPeriod/startDate',
    '/tender/enquiryPeriod/endDate',
    '/tender/enquiryPeriod/maxExtentDate',
    '/tender/enquiryPeriod/durationInDays',
    '/tender/tenderPeriod/startDate',
    '/tender/tenderPeriod/endDate',
    '/tender/tenderPeriod/maxExtentDate',
    '/tender/tenderPeriod/durationInDays',
    '/tender/minValue/amount',
    '/tender/minValue/currency',
    '/tender/value/amount',
    '/tender/value/currency',
    '/tender/items/0/id',
    '/tender/items/0/description',
    '/tender/items/0/quantity',
    '/tender/items/0/unit/scheme',
    '/tender/items/0/unit/id',
    '/tender/items/0/unit/name',
    '/tender/items/0/unit/uri',
    '/tender/items/0/unit/value/amount',
    '/tender/items/0/unit/value/currency',
    '/tender/items/0/additionalClassifications/0/scheme',
    '/tender/items/0/additionalClassifications/0/id',
    '/tender/items/0/additionalClassifications/0/description',
    '/tender/items/0/additionalClassifications/0/uri',
    '/tender/items/0/classification/scheme',
    '/tender/items/0/classification/id',
    '/tender/items/0/classification/description',
    '/tender/items/0/classification/uri',
    '/tender/procuringEntity/name',
    '/tender/procuringEntity/id'
]


awards_columns = [
    '/ocid',
    '/awards/id',
    '/awards/title',
    '/awards/description',
    '/awards/status',
    '/awards/date',
    '/awards/contractPeriod/startDate',
    '/awards/contractPeriod/endDate',
    '/awards/contractPeriod/maxExtentDate',
    '/awards/contractPeriod/durationInDays',
    '/awards/value/amount',
    '/awards/value/currency'
]
awards_combined_columns = [
    '/ocid',
    '/awards/id',
    '/awards/title',
    '/awards/description',
    '/awards/status',
    '/awards/date',
    '/awards/amendments/0/date',
    '/awards/amendments/0/rationale',
    '/awards/amendments/0/id',
    '/awards/amendments/0/description',
    '/awards/amendments/0/amendsReleaseID',
    '/awards/amendments/0/releaseID',
    '/awards/documents/0/id',
    '/awards/documents/0/documentType',
    '/awards/documents/0/title',
    '/awards/documents/0/description',
    '/awards/documents/0/url',
    '/awards/documents/0/datePublished',
    '/awards/documents/0/dateModified',
    '/awards/documents/0/format',
    '/awards/documents/0/language',
    '/awards/contractPeriod/startDate',
    '/awards/contractPeriod/endDate',
    '/awards/contractPeriod/maxExtentDate',
    '/awards/contractPeriod/durationInDays',
    '/awards/items/0/id',
    '/awards/items/0/description',
    '/awards/items/0/quantity',
    '/awards/items/0/unit/scheme',
    '/awards/items/0/unit/id',
    '/awards/items/0/unit/name',
    '/awards/items/0/unit/uri',
    '/awards/items/0/unit/value/amount',
    '/awards/items/0/unit/value/currency',
    '/awards/items/0/additionalClassifications/0/scheme',
    '/awards/items/0/additionalClassifications/0/id',
    '/awards/items/0/additionalClassifications/0/description',
    '/awards/items/0/additionalClassifications/0/uri',
    '/awards/items/0/classification/scheme',
    '/awards/items/0/classification/id',
    '/awards/items/0/classification/description',
    '/awards/items/0/classification/uri',
    '/awards/suppliers/0/name',
    '/awards/suppliers/0/id',
    '/awards/value/amount',
    '/awards/value/currency'
]

awards_arrays = [
    '/awards/suppliers',
    '/awards/items',
    '/awards/documents',
    '/awards/amendments',
    '/awards/items/additionalClassifications'
]
contracts_columns = [
    '/ocid',
    '/contracts/id',
    '/contracts/awardID',
    '/contracts/title',
    '/contracts/description',
    '/contracts/status',
    '/contracts/dateSigned',
    '/contracts/value/amount',
    '/contracts/value/currency',
    '/contracts/period/startDate',
    '/contracts/period/endDate',
    '/contracts/period/maxExtentDate',
    '/contracts/period/durationInDays'
]
contracts_arrays = [
    '/contracts/items',
    '/contracts/documents',
    '/contracts/relatedProcesses',
    '/contracts/milestones',
    '/contracts/amendments',
    '/contracts/relatedProcesses/relationship',
    '/contracts/implementation/transactions',
    '/contracts/implementation/milestones',
    '/contracts/implementation/documents',
    '/contracts/items/additionalClassifications'
]
contracts_combined_columns = [
    '/ocid',
    '/contracts/id',
    '/contracts/awardID',
    '/contracts/title',
    '/contracts/description',
    '/contracts/status',
    '/contracts/dateSigned',
    '/contracts/amendments/0/date',
    '/contracts/amendments/0/rationale',
    '/contracts/amendments/0/id',
    '/contracts/amendments/0/description',
    '/contracts/amendments/0/amendsReleaseID',
    '/contracts/amendments/0/releaseID',
    '/contracts/milestones/0/id',
    '/contracts/milestones/0/title',
    '/contracts/milestones/0/type',
    '/contracts/milestones/0/description',
    '/contracts/milestones/0/code',
    '/contracts/milestones/0/dueDate',
    '/contracts/milestones/0/dateMet',
    '/contracts/milestones/0/dateModified',
    '/contracts/milestones/0/status',
    '/contracts/relatedProcesses/0/id',
    '/contracts/relatedProcesses/0/relationship/0',
    '/contracts/relatedProcesses/0/title',
    '/contracts/relatedProcesses/0/scheme',
    '/contracts/relatedProcesses/0/identifier',
    '/contracts/relatedProcesses/0/uri',
    '/contracts/implementation/documents/0/id',
    '/contracts/implementation/documents/0/documentType',
    '/contracts/implementation/documents/0/title',
    '/contracts/implementation/documents/0/description',
    '/contracts/implementation/documents/0/url',
    '/contracts/implementation/documents/0/datePublished',
    '/contracts/implementation/documents/0/dateModified',
    '/contracts/implementation/documents/0/format',
    '/contracts/implementation/documents/0/language',
    '/contracts/implementation/milestones/0/id',
    '/contracts/implementation/milestones/0/title',
    '/contracts/implementation/milestones/0/type',
    '/contracts/implementation/milestones/0/description',
    '/contracts/implementation/milestones/0/code',
    '/contracts/implementation/milestones/0/dueDate',
    '/contracts/implementation/milestones/0/dateMet',
    '/contracts/implementation/milestones/0/dateModified',
    '/contracts/implementation/milestones/0/status',
    '/contracts/implementation/transactions/0/id',
    '/contracts/implementation/transactions/0/source',
    '/contracts/implementation/transactions/0/date',
    '/contracts/implementation/transactions/0/uri',
    '/contracts/implementation/transactions/0/payee/name',
    '/contracts/implementation/transactions/0/payee/id',
    '/contracts/implementation/transactions/0/payer/name',
    '/contracts/implementation/transactions/0/payer/id',
    '/contracts/implementation/transactions/0/value/amount',
    '/contracts/implementation/transactions/0/value/currency',
    '/contracts/documents/0/id',
    '/contracts/documents/0/documentType',
    '/contracts/documents/0/title',
    '/contracts/documents/0/description',
    '/contracts/documents/0/url',
    '/contracts/documents/0/datePublished',
    '/contracts/documents/0/dateModified',
    '/contracts/documents/0/format',
    '/contracts/documents/0/language',
    '/contracts/items/0/id',
    '/contracts/items/0/description',
    '/contracts/items/0/quantity',
    '/contracts/items/0/unit/scheme',
    '/contracts/items/0/unit/id',
    '/contracts/items/0/unit/name',
    '/contracts/items/0/unit/uri',
    '/contracts/items/0/unit/value/amount',
    '/contracts/items/0/unit/value/currency',
    '/contracts/items/0/additionalClassifications/0/scheme',
    '/contracts/items/0/additionalClassifications/0/id',
    '/contracts/items/0/additionalClassifications/0/description',
    '/contracts/items/0/additionalClassifications/0/uri',
    '/contracts/items/0/classification/scheme',
    '/contracts/items/0/classification/id',
    '/contracts/items/0/classification/description',
    '/contracts/items/0/classification/uri',
    '/contracts/value/amount',
    '/contracts/value/currency',
    '/contracts/period/startDate',
    '/contracts/period/endDate',
    '/contracts/period/maxExtentDate',
    '/contracts/period/durationInDays'
]

planning_columns = [
    '/ocid',
    '/planning/rationale',
    '/planning/budget/id',
    '/planning/budget/description',
    '/planning/budget/project',
    '/planning/budget/projectID',
    '/planning/budget/uri',
    '/planning/budget/amount/amount',
    '/planning/budget/amount/currency'
]

planning_combined_columns = [
    '/ocid',
    '/planning/rationale',
    '/planning/milestones/0/id',
    '/planning/milestones/0/title',
    '/planning/milestones/0/type',
    '/planning/milestones/0/description',
    '/planning/milestones/0/code',
    '/planning/milestones/0/dueDate',
    '/planning/milestones/0/dateMet',
    '/planning/milestones/0/dateModified',
    '/planning/milestones/0/status',
    '/planning/documents/0/id',
    '/planning/documents/0/documentType',
    '/planning/documents/0/title',
    '/planning/documents/0/description',
    '/planning/documents/0/url',
    '/planning/documents/0/datePublished',
    '/planning/documents/0/dateModified',
    '/planning/documents/0/format',
    '/planning/documents/0/language',
    '/planning/budget/id',
    '/planning/budget/description',
    '/planning/budget/project',
    '/planning/budget/projectID',
    '/planning/budget/uri',
    '/planning/budget/amount/amount',
    '/planning/budget/amount/currency'
]
planning_arrays = ['/planning/documents', '/planning/milestones']
parties_arrays = ['/parties/additionalIdentifiers', '/parties/roles']
parties_columns = [
    '/ocid',
    '/parties/name',
    '/parties/id',
    '/parties/contactPoint/name',
    '/parties/contactPoint/email',
    '/parties/contactPoint/telephone',
    '/parties/contactPoint/faxNumber',
    '/parties/contactPoint/url',
    '/parties/address/streetAddress',
    '/parties/address/locality',
    '/parties/address/region',
    '/parties/address/postalCode',
    '/parties/address/countryName',
    '/parties/identifier/scheme',
    '/parties/identifier/id',
    '/parties/identifier/legalName',
    '/parties/identifier/uri'
]
parties_combined_columns = [
    '/ocid',
    '/parties/name',
    '/parties/id',
    '/parties/roles/0',
    '/parties/contactPoint/name',
    '/parties/contactPoint/email',
    '/parties/contactPoint/telephone',
    '/parties/contactPoint/faxNumber',
    '/parties/contactPoint/url',
    '/parties/address/streetAddress',
    '/parties/address/locality',
    '/parties/address/region',
    '/parties/address/postalCode',
    '/parties/address/countryName',
    '/parties/additionalIdentifiers/0/scheme',
    '/parties/additionalIdentifiers/0/id',
    '/parties/additionalIdentifiers/0/legalName',
    '/parties/additionalIdentifiers/0/uri',
    '/parties/identifier/scheme',
    '/parties/identifier/id',
    '/parties/identifier/legalName',
    '/parties/identifier/uri'
]


titles = {
    '/awards/amendments/0/amendsReleaseID': 'Amendment Amended Release (identifier)',
    '/awards/amendments/0/date': 'Amendment Date',
    '/awards/amendments/0/description': 'Amendment Description',
    '/awards/amendments/0/id': 'Amendment Id',
    '/awards/amendments/0/rationale': 'Amendment Rationale',
    '/awards/amendments/0/releaseID': 'Amendment Amending Release (identifier)',
    '/awards/amendments/amendsReleaseID': 'Amendment Amended Release (identifier)',
    '/awards/amendments/date': 'Amendment Date',
    '/awards/amendments/description': 'Amendment Description',
    '/awards/amendments/id': 'Amendment Id',
    '/awards/amendments/rationale': 'Amendment Rationale',
    '/awards/amendments/releaseID': 'Amendment Amending Release (identifier)',
    '/awards/contractPeriod/durationInDays': 'Contract Period Duration (days)',
    '/awards/contractPeriod/endDate': 'Contract Period End Date',
    '/awards/contractPeriod/maxExtentDate': 'Contract Period Maximum Extent',
    '/awards/contractPeriod/startDate': 'Contract Period Start Date',
    '/awards/date': 'Award Date',
    '/awards/description': 'Award Description',
    '/awards/documents/0/dateModified': 'Document Date Modified',
    '/awards/documents/0/datePublished': 'Document Date Published',
    '/awards/documents/0/description': 'Document Description',
    '/awards/documents/0/documentType': 'Document Type',
    '/awards/documents/0/format': 'Document Format',
    '/awards/documents/0/id': 'Document Id',
    '/awards/documents/0/language': 'Document Language',
    '/awards/documents/0/title': 'Document Title',
    '/awards/documents/0/url': 'Document Url',
    '/awards/documents/dateModified': 'Document Date Modified',
    '/awards/documents/datePublished': 'Document Date Published',
    '/awards/documents/description': 'Document Description',
    '/awards/documents/documentType': 'Document Type',
    '/awards/documents/format': 'Document Format',
    '/awards/documents/id': 'Document Id',
    '/awards/documents/language': 'Document Language',
    '/awards/documents/title': 'Document Title',
    '/awards/documents/url': 'Document Url',
    '/awards/id': 'Award Id',
    '/awards/items/0/additionalClassifications/0/description': 'Classification '
    'Description',
    '/awards/items/0/additionalClassifications/0/id': 'Classification Id',
    '/awards/items/0/additionalClassifications/0/scheme': 'Classification Scheme',
    '/awards/items/0/additionalClassifications/0/uri': 'Classification Uri',
    '/awards/items/0/classification/description': 'Classification Description',
    '/awards/items/0/classification/id': 'Classification Id',
    '/awards/items/0/classification/scheme': 'Classification Scheme',
    '/awards/items/0/classification/uri': 'Classification Uri',
    '/awards/items/0/description': 'Item Description',
    '/awards/items/0/id': 'Item Id',
    '/awards/items/0/quantity': 'Item Quantity',
    '/awards/items/0/unit/id': 'Unit Id',
    '/awards/items/0/unit/name': 'Unit Name',
    '/awards/items/0/unit/scheme': 'Unit Scheme',
    '/awards/items/0/unit/uri': 'Unit Uri',
    '/awards/items/0/unit/value/amount': 'Value Amount',
    '/awards/items/0/unit/value/currency': 'Value Currency',
    '/awards/items/additionalClassifications/description': 'Classification '
    'Description',
    '/awards/items/additionalClassifications/id': 'Classification Id',
    '/awards/items/additionalClassifications/scheme': 'Classification Scheme',
    '/awards/items/additionalClassifications/uri': 'Classification Uri',
    '/awards/items/classification/description': 'Classification Description',
    '/awards/items/classification/id': 'Classification Id',
    '/awards/items/classification/scheme': 'Classification Scheme',
    '/awards/items/classification/uri': 'Classification Uri',
    '/awards/items/description': 'Item Description',
    '/awards/items/id': 'Item Id',
    '/awards/items/quantity': 'Item Quantity',
    '/awards/items/unit/id': 'Unit Id',
    '/awards/items/unit/name': 'Unit Name',
    '/awards/items/unit/scheme': 'Unit Scheme',
    '/awards/items/unit/uri': 'Unit Uri',
    '/awards/items/unit/value/amount': 'Value Amount',
    '/awards/items/unit/value/currency': 'Value Currency',
    '/awards/status': 'Award Status',
    '/awards/suppliers/0/id': 'Organization Reference Id',
    '/awards/suppliers/0/name': 'Organization Reference Name',
    '/awards/suppliers/id': 'Organization Reference Id',
    '/awards/suppliers/name': 'Organization Reference Name',
    '/awards/title': 'Award Title',
    '/awards/value/amount': 'Value Amount',
    '/awards/value/currency': 'Value Currency',
    '/contracts/amendments/0/amendsReleaseID': 'Amendment Amended Release '
    '(identifier)',
    '/contracts/amendments/0/date': 'Amendment Date',
    '/contracts/amendments/0/description': 'Amendment Description',
    '/contracts/amendments/0/id': 'Amendment Id',
    '/contracts/amendments/0/rationale': 'Amendment Rationale',
    '/contracts/amendments/0/releaseID': 'Amendment Amending Release (identifier)',
    '/contracts/amendments/amendsReleaseID': 'Amendment Amended Release '
    '(identifier)',
    '/contracts/amendments/date': 'Amendment Date',
    '/contracts/amendments/description': 'Amendment Description',
    '/contracts/amendments/id': 'Amendment Id',
    '/contracts/amendments/rationale': 'Amendment Rationale',
    '/contracts/amendments/releaseID': 'Amendment Amending Release (identifier)',
    '/contracts/awardID': 'Contract Award Id',
    '/contracts/dateSigned': 'Contract Date Signed',
    '/contracts/description': 'Contract Description',
    '/contracts/documents/0/dateModified': 'Document Date Modified',
    '/contracts/documents/0/datePublished': 'Document Date Published',
    '/contracts/documents/0/description': 'Document Description',
    '/contracts/documents/0/documentType': 'Document Type',
    '/contracts/documents/0/format': 'Document Format',
    '/contracts/documents/0/id': 'Document Id',
    '/contracts/documents/0/language': 'Document Language',
    '/contracts/documents/0/title': 'Document Title',
    '/contracts/documents/0/url': 'Document Url',
    '/contracts/documents/dateModified': 'Document Date Modified',
    '/contracts/documents/datePublished': 'Document Date Published',
    '/contracts/documents/description': 'Document Description',
    '/contracts/documents/documentType': 'Document Type',
    '/contracts/documents/format': 'Document Format',
    '/contracts/documents/id': 'Document Id',
    '/contracts/documents/language': 'Document Language',
    '/contracts/documents/title': 'Document Title',
    '/contracts/documents/url': 'Document Url',
    '/contracts/id': 'Contract Id',
    '/contracts/implementation/documents/0/dateModified': 'Document Date Modified',
    '/contracts/implementation/documents/0/datePublished': 'Document Date '
    'Published',
    '/contracts/implementation/documents/0/description': 'Document Description',
    '/contracts/implementation/documents/0/documentType': 'Document Type',
    '/contracts/implementation/documents/0/format': 'Document Format',
    '/contracts/implementation/documents/0/id': 'Document Id',
    '/contracts/implementation/documents/0/language': 'Document Language',
    '/contracts/implementation/documents/0/title': 'Document Title',
    '/contracts/implementation/documents/0/url': 'Document Url',
    '/contracts/implementation/documents/dateModified': 'Document Date Modified',
    '/contracts/implementation/documents/datePublished': 'Document Date Published',
    '/contracts/implementation/documents/description': 'Document Description',
    '/contracts/implementation/documents/documentType': 'Document Type',
    '/contracts/implementation/documents/format': 'Document Format',
    '/contracts/implementation/documents/id': 'Document Id',
    '/contracts/implementation/documents/language': 'Document Language',
    '/contracts/implementation/documents/title': 'Document Title',
    '/contracts/implementation/documents/url': 'Document Url',
    '/contracts/implementation/milestones/0/code': 'Milestone Code',
    '/contracts/implementation/milestones/0/dateMet': 'Milestone Date Met',
    '/contracts/implementation/milestones/0/dateModified': 'Milestone Date '
    'Modified',
    '/contracts/implementation/milestones/0/description': 'Milestone Description',
    '/contracts/implementation/milestones/0/dueDate': 'Milestone Due Date',
    '/contracts/implementation/milestones/0/id': 'Milestone Id',
    '/contracts/implementation/milestones/0/status': 'Milestone Status',
    '/contracts/implementation/milestones/0/title': 'Milestone Title',
    '/contracts/implementation/milestones/0/type': 'Milestone Type',
    '/contracts/implementation/milestones/code': 'Milestone Code',
    '/contracts/implementation/milestones/dateMet': 'Milestone Date Met',
    '/contracts/implementation/milestones/dateModified': 'Milestone Date Modified',
    '/contracts/implementation/milestones/description': 'Milestone Description',
    '/contracts/implementation/milestones/dueDate': 'Milestone Due Date',
    '/contracts/implementation/milestones/id': 'Milestone Id',
    '/contracts/implementation/milestones/status': 'Milestone Status',
    '/contracts/implementation/milestones/title': 'Milestone Title',
    '/contracts/implementation/milestones/type': 'Milestone Type',
    '/contracts/implementation/transactions/0/date': 'Transaction Information '
    'Date',
    '/contracts/implementation/transactions/0/id': 'Transaction Information Id',
    '/contracts/implementation/transactions/0/payee/id': 'Payee Organization Id',
    '/contracts/implementation/transactions/0/payee/name': 'Payee Organization '
    'Name',
    '/contracts/implementation/transactions/0/payer/id': 'Payer Organization Id',
    '/contracts/implementation/transactions/0/payer/name': 'Payer Organization '
    'Name',
    '/contracts/implementation/transactions/0/source': 'Transaction Information '
    'Data Source',
    '/contracts/implementation/transactions/0/uri': 'Transaction Information '
    'Linked Spending',
    '/contracts/implementation/transactions/0/value/amount': 'Value Amount',
    '/contracts/implementation/transactions/0/value/currency': 'Value Currency',
    '/contracts/implementation/transactions/date': 'Transaction Information Date',
    '/contracts/implementation/transactions/id': 'Transaction Information Id',
    '/contracts/implementation/transactions/payee/id': 'Payee Organization Id',
    '/contracts/implementation/transactions/payee/name': 'Payee Organization Name',
    '/contracts/implementation/transactions/payer/id': 'Payer Organization Id',
    '/contracts/implementation/transactions/payer/name': 'Payer Organization Name',
    '/contracts/implementation/transactions/source': 'Transaction Information '
    'Data Source',
    '/contracts/implementation/transactions/uri': 'Transaction Information Linked '
    'Spending',
    '/contracts/implementation/transactions/value/amount': 'Value Amount',
    '/contracts/implementation/transactions/value/currency': 'Value Currency',
    '/contracts/items/0/additionalClassifications/0/description': 'Classification '
    'Description',
    '/contracts/items/0/additionalClassifications/0/id': 'Classification Id',
    '/contracts/items/0/additionalClassifications/0/scheme': 'Classification '
    'Scheme',
    '/contracts/items/0/additionalClassifications/0/uri': 'Classification Uri',
    '/contracts/items/0/classification/description': 'Classification Description',
    '/contracts/items/0/classification/id': 'Classification Id',
    '/contracts/items/0/classification/scheme': 'Classification Scheme',
    '/contracts/items/0/classification/uri': 'Classification Uri',
    '/contracts/items/0/description': 'Item Description',
    '/contracts/items/0/id': 'Item Id',
    '/contracts/items/0/quantity': 'Item Quantity',
    '/contracts/items/0/unit/id': 'Unit Id',
    '/contracts/items/0/unit/name': 'Unit Name',
    '/contracts/items/0/unit/scheme': 'Unit Scheme',
    '/contracts/items/0/unit/uri': 'Unit Uri',
    '/contracts/items/0/unit/value/amount': 'Value Amount',
    '/contracts/items/0/unit/value/currency': 'Value Currency',
    '/contracts/items/additionalClassifications/description': 'Classification '
    'Description',
    '/contracts/items/additionalClassifications/id': 'Classification Id',
    '/contracts/items/additionalClassifications/scheme': 'Classification Scheme',
    '/contracts/items/additionalClassifications/uri': 'Classification Uri',
    '/contracts/items/classification/description': 'Classification Description',
    '/contracts/items/classification/id': 'Classification Id',
    '/contracts/items/classification/scheme': 'Classification Scheme',
    '/contracts/items/classification/uri': 'Classification Uri',
    '/contracts/items/description': 'Item Description',
    '/contracts/items/id': 'Item Id',
    '/contracts/items/quantity': 'Item Quantity',
    '/contracts/items/unit/id': 'Unit Id',
    '/contracts/items/unit/name': 'Unit Name',
    '/contracts/items/unit/scheme': 'Unit Scheme',
    '/contracts/items/unit/uri': 'Unit Uri',
    '/contracts/items/unit/value/amount': 'Value Amount',
    '/contracts/items/unit/value/currency': 'Value Currency',
    '/contracts/milestones/0/code': 'Milestone Code',
    '/contracts/milestones/0/dateMet': 'Milestone Date Met',
    '/contracts/milestones/0/dateModified': 'Milestone Date Modified',
    '/contracts/milestones/0/description': 'Milestone Description',
    '/contracts/milestones/0/dueDate': 'Milestone Due Date',
    '/contracts/milestones/0/id': 'Milestone Id',
    '/contracts/milestones/0/status': 'Milestone Status',
    '/contracts/milestones/0/title': 'Milestone Title',
    '/contracts/milestones/0/type': 'Milestone Type',
    '/contracts/milestones/code': 'Milestone Code',
    '/contracts/milestones/dateMet': 'Milestone Date Met',
    '/contracts/milestones/dateModified': 'Milestone Date Modified',
    '/contracts/milestones/description': 'Milestone Description',
    '/contracts/milestones/dueDate': 'Milestone Due Date',
    '/contracts/milestones/id': 'Milestone Id',
    '/contracts/milestones/status': 'Milestone Status',
    '/contracts/milestones/title': 'Milestone Title',
    '/contracts/milestones/type': 'Milestone Type',
    '/contracts/period/durationInDays': 'Period Duration (days)',
    '/contracts/period/endDate': 'Period End Date',
    '/contracts/period/maxExtentDate': 'Period Maximum Extent',
    '/contracts/period/startDate': 'Period Start Date',
    '/contracts/relatedProcesses/0/id': 'Related Process Relationship Id',
    '/contracts/relatedProcesses/0/identifier': 'Related Process Identifier',
    '/contracts/relatedProcesses/0/relationship/0': 'Related Process Relationship',
    '/contracts/relatedProcesses/0/scheme': 'Related Process Scheme',
    '/contracts/relatedProcesses/0/title': 'Related Process Title',
    '/contracts/relatedProcesses/0/uri': 'Related Process Uri',
    '/contracts/relatedProcesses/id': 'Related Process Relationship Id',
    '/contracts/relatedProcesses/identifier': 'Related Process Identifier',
    '/contracts/relatedProcesses/relationship': 'Related Process Relationship',
    '/contracts/relatedProcesses/scheme': 'Related Process Scheme',
    '/contracts/relatedProcesses/title': 'Related Process Title',
    '/contracts/relatedProcesses/uri': 'Related Process Uri',
    '/contracts/status': 'Contract Status',
    '/contracts/title': 'Contract Title',
    '/contracts/value/amount': 'Value Amount',
    '/contracts/value/currency': 'Value Currency',
    '/ocid': 'Open Contracting Id',
    '/parties/additionalIdentifiers/0/id': 'Identifier Id',
    '/parties/additionalIdentifiers/0/legalName': 'Identifier Legal Name',
    '/parties/additionalIdentifiers/0/scheme': 'Identifier Scheme',
    '/parties/additionalIdentifiers/0/uri': 'Identifier Uri',
    '/parties/additionalIdentifiers/id': 'Identifier Id',
    '/parties/additionalIdentifiers/legalName': 'Identifier Legal Name',
    '/parties/additionalIdentifiers/scheme': 'Identifier Scheme',
    '/parties/additionalIdentifiers/uri': 'Identifier Uri',
    '/parties/address/countryName': 'Address Country Name',
    '/parties/address/locality': 'Address Locality',
    '/parties/address/postalCode': 'Address Postal Code',
    '/parties/address/region': 'Address Region',
    '/parties/address/streetAddress': 'Address Street',
    '/parties/contactPoint/email': 'Contact Point Email',
    '/parties/contactPoint/faxNumber': 'Contact Point Fax Number',
    '/parties/contactPoint/name': 'Contact Point Name',
    '/parties/contactPoint/telephone': 'Contact Point Telephone',
    '/parties/contactPoint/url': 'Contact Point Url',
    '/parties/id': 'Organization Entity Id',
    '/parties/identifier/id': 'Primary Identifier Id',
    '/parties/identifier/legalName': 'Primary Identifier Legal Name',
    '/parties/identifier/scheme': 'Primary Identifier Scheme',
    '/parties/identifier/uri': 'Primary Identifier Uri',
    '/parties/name': 'Organization Common Name',
    '/parties/roles': 'Organization Party Roles',
    '/parties/roles/0': 'Organization Party Roles',
    '/planning/budget/amount/amount': 'Amount',
    '/planning/budget/amount/currency': 'Amount Currency',
    '/planning/budget/description': 'Budget Source',
    '/planning/budget/id': 'Budget Id',
    '/planning/budget/project': 'Budget Project Title',
    '/planning/budget/projectID': 'Budget Project Identifier',
    '/planning/budget/uri': 'Budget Linked Information',
    '/planning/documents/0/dateModified': 'Document Date Modified',
    '/planning/documents/0/datePublished': 'Document Date Published',
    '/planning/documents/0/description': 'Document Description',
    '/planning/documents/0/documentType': 'Document Type',
    '/planning/documents/0/format': 'Document Format',
    '/planning/documents/0/id': 'Document Id',
    '/planning/documents/0/language': 'Document Language',
    '/planning/documents/0/title': 'Document Title',
    '/planning/documents/0/url': 'Document Url',
    '/planning/documents/dateModified': 'Document Date Modified',
    '/planning/documents/datePublished': 'Document Date Published',
    '/planning/documents/description': 'Document Description',
    '/planning/documents/documentType': 'Document Type',
    '/planning/documents/format': 'Document Format',
    '/planning/documents/id': 'Document Id',
    '/planning/documents/language': 'Document Language',
    '/planning/documents/title': 'Document Title',
    '/planning/documents/url': 'Document Url',
    '/planning/milestones/0/code': 'Milestone Code',
    '/planning/milestones/0/dateMet': 'Milestone Date Met',
    '/planning/milestones/0/dateModified': 'Milestone Date Modified',
    '/planning/milestones/0/description': 'Milestone Description',
    '/planning/milestones/0/dueDate': 'Milestone Due Date',
    '/planning/milestones/0/id': 'Milestone Id',
    '/planning/milestones/0/status': 'Milestone Status',
    '/planning/milestones/0/title': 'Milestone Title',
    '/planning/milestones/0/type': 'Milestone Type',
    '/planning/milestones/code': 'Milestone Code',
    '/planning/milestones/dateMet': 'Milestone Date Met',
    '/planning/milestones/dateModified': 'Milestone Date Modified',
    '/planning/milestones/description': 'Milestone Description',
    '/planning/milestones/dueDate': 'Milestone Due Date',
    '/planning/milestones/id': 'Milestone Id',
    '/planning/milestones/status': 'Milestone Status',
    '/planning/milestones/title': 'Milestone Title',
    '/planning/milestones/type': 'Milestone Type',
    '/planning/rationale': 'Planning Rationale',
    '/tender/additionalProcurementCategories': 'Tender Additional Procurement '
    'Categories',
    '/tender/additionalProcurementCategories/0': 'Tender Additional Procurement '
    'Categories',
    '/tender/amendments/0/amendsReleaseID': 'Amendment Amended Release '
    '(identifier)',
    '/tender/amendments/0/date': 'Amendment Date',
    '/tender/amendments/0/description': 'Amendment Description',
    '/tender/amendments/0/id': 'Amendment Id',
    '/tender/amendments/0/rationale': 'Amendment Rationale',
    '/tender/amendments/0/releaseID': 'Amendment Amending Release (identifier)',
    '/tender/amendments/amendsReleaseID': 'Amendment Amended Release (identifier)',
    '/tender/amendments/date': 'Amendment Date',
    '/tender/amendments/description': 'Amendment Description',
    '/tender/amendments/id': 'Amendment Id',
    '/tender/amendments/rationale': 'Amendment Rationale',
    '/tender/amendments/releaseID': 'Amendment Amending Release (identifier)',
    '/tender/awardCriteria': 'Tender Award Criteria',
    '/tender/awardCriteriaDetails': 'Tender Award Criteria Details',
    '/tender/awardPeriod/durationInDays': 'Evaluation And Award Period Duration '
    '(days)',
    '/tender/awardPeriod/endDate': 'Evaluation And Award Period End Date',
    '/tender/awardPeriod/maxExtentDate': 'Evaluation And Award Period Maximum '
    'Extent',
    '/tender/awardPeriod/startDate': 'Evaluation And Award Period Start Date',
    '/tender/contractPeriod/durationInDays': 'Contract Period Duration (days)',
    '/tender/contractPeriod/endDate': 'Contract Period End Date',
    '/tender/contractPeriod/maxExtentDate': 'Contract Period Maximum Extent',
    '/tender/contractPeriod/startDate': 'Contract Period Start Date',
    '/tender/description': 'Tender Description',
    '/tender/documents/0/dateModified': 'Document Date Modified',
    '/tender/documents/0/datePublished': 'Document Date Published',
    '/tender/documents/0/description': 'Document Description',
    '/tender/documents/0/documentType': 'Document Type',
    '/tender/documents/0/format': 'Document Format',
    '/tender/documents/0/id': 'Document Id',
    '/tender/documents/0/language': 'Document Language',
    '/tender/documents/0/title': 'Document Title',
    '/tender/documents/0/url': 'Document Url',
    '/tender/documents/dateModified': 'Document Date Modified',
    '/tender/documents/datePublished': 'Document Date Published',
    '/tender/documents/description': 'Document Description',
    '/tender/documents/documentType': 'Document Type',
    '/tender/documents/format': 'Document Format',
    '/tender/documents/id': 'Document Id',
    '/tender/documents/language': 'Document Language',
    '/tender/documents/title': 'Document Title',
    '/tender/documents/url': 'Document Url',
    '/tender/eligibilityCriteria': 'Tender Eligibility Criteria',
    '/tender/enquiryPeriod/durationInDays': 'Enquiry Period Duration (days)',
    '/tender/enquiryPeriod/endDate': 'Enquiry Period End Date',
    '/tender/enquiryPeriod/maxExtentDate': 'Enquiry Period Maximum Extent',
    '/tender/enquiryPeriod/startDate': 'Enquiry Period Start Date',
    '/tender/hasEnquiries': 'Tender Has Enquiries?',
    '/tender/id': 'Tender Id',
    '/tender/items/0/additionalClassifications/0/description': 'Classification '
    'Description',
    '/tender/items/0/additionalClassifications/0/id': 'Classification Id',
    '/tender/items/0/additionalClassifications/0/scheme': 'Classification Scheme',
    '/tender/items/0/additionalClassifications/0/uri': 'Classification Uri',
    '/tender/items/0/classification/description': 'Classification Description',
    '/tender/items/0/classification/id': 'Classification Id',
    '/tender/items/0/classification/scheme': 'Classification Scheme',
    '/tender/items/0/classification/uri': 'Classification Uri',
    '/tender/items/0/description': 'Item Description',
    '/tender/items/0/id': 'Item Id',
    '/tender/items/0/quantity': 'Item Quantity',
    '/tender/items/0/unit/id': 'Unit Id',
    '/tender/items/0/unit/name': 'Unit Name',
    '/tender/items/0/unit/scheme': 'Unit Scheme',
    '/tender/items/0/unit/uri': 'Unit Uri',
    '/tender/items/0/unit/value/amount': 'Value Amount',
    '/tender/items/0/unit/value/currency': 'Value Currency',
    '/tender/items/additionalClassifications/description': 'Classification '
    'Description',
    '/tender/items/additionalClassifications/id': 'Classification Id',
    '/tender/items/additionalClassifications/scheme': 'Classification Scheme',
    '/tender/items/additionalClassifications/uri': 'Classification Uri',
    '/tender/items/classification/description': 'Classification Description',
    '/tender/items/classification/id': 'Classification Id',
    '/tender/items/classification/scheme': 'Classification Scheme',
    '/tender/items/classification/uri': 'Classification Uri',
    '/tender/items/description': 'Item Description',
    '/tender/items/id': 'Item Id',
    '/tender/items/quantity': 'Item Quantity',
    '/tender/items/unit/id': 'Unit Id',
    '/tender/items/unit/name': 'Unit Name',
    '/tender/items/unit/scheme': 'Unit Scheme',
    '/tender/items/unit/uri': 'Unit Uri',
    '/tender/items/unit/value/amount': 'Value Amount',
    '/tender/items/unit/value/currency': 'Value Currency',
    '/tender/mainProcurementCategory': 'Tender Main Procurement Category',
    '/tender/milestones/0/code': 'Milestone Code',
    '/tender/milestones/0/dateMet': 'Milestone Date Met',
    '/tender/milestones/0/dateModified': 'Milestone Date Modified',
    '/tender/milestones/0/description': 'Milestone Description',
    '/tender/milestones/0/dueDate': 'Milestone Due Date',
    '/tender/milestones/0/id': 'Milestone Id',
    '/tender/milestones/0/status': 'Milestone Status',
    '/tender/milestones/0/title': 'Milestone Title',
    '/tender/milestones/0/type': 'Milestone Type',
    '/tender/milestones/code': 'Milestone Code',
    '/tender/milestones/dateMet': 'Milestone Date Met',
    '/tender/milestones/dateModified': 'Milestone Date Modified',
    '/tender/milestones/description': 'Milestone Description',
    '/tender/milestones/dueDate': 'Milestone Due Date',
    '/tender/milestones/id': 'Milestone Id',
    '/tender/milestones/status': 'Milestone Status',
    '/tender/milestones/title': 'Milestone Title',
    '/tender/milestones/type': 'Milestone Type',
    '/tender/minValue/amount': 'Minimum Value Amount',
    '/tender/minValue/currency': 'Minimum Value Currency',
    '/tender/numberOfTenderers': 'Tender Number Of Tenderers',
    '/tender/procurementMethod': 'Tender Procurement Method',
    '/tender/procurementMethodDetails': 'Tender Procurement Method Details',
    '/tender/procurementMethodRationale': 'Tender Procurement Method Rationale',
    '/tender/procuringEntity/id': 'Procuring Entity Organization Id',
    '/tender/procuringEntity/name': 'Procuring Entity Organization Name',
    '/tender/status': 'Tender Status',
    '/tender/submissionMethod': 'Tender Submission Method',
    '/tender/submissionMethod/0': 'Tender Submission Method',
    '/tender/submissionMethod/0Details': 'Tender Submission Method Details',
    '/tender/submissionMethodDetails': 'Tender Submission Method Details',
    '/tender/tenderPeriod/durationInDays': 'Tender Period Duration (days)',
    '/tender/tenderPeriod/endDate': 'Tender Period End Date',
    '/tender/tenderPeriod/maxExtentDate': 'Tender Period Maximum Extent',
    '/tender/tenderPeriod/startDate': 'Tender Period Start Date',
    '/tender/tenderers/0/id': 'Organization Reference Id',
    '/tender/tenderers/0/name': 'Organization Reference Name',
    '/tender/tenderers/id': 'Organization Reference Id',
    '/tender/tenderers/name': 'Organization Reference Name',
    '/tender/title': 'Tender Title',
    '/tender/value/amount': 'Value Amount',
    '/tender/value/currency': 'Value Currency'
}

