name: CI
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        # openpyxl > 3.1.2 fixes deprecation warning in python 3.12.
        # https://foss.heptapod.net/openpyxl/openpyxl/-/issues/2051
        python-version: [3.8, 3.9, '3.10', '3.11']  # 3.12
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.cfg
      - run: pip install .[test] babel
      - run: pybabel compile -f -d spoonbill/locale -D spoonbill
      - run: pytest -W error --cov spoonbill
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
