name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    with:
      python-version: '3.10'
      # test_requirements.py doesn't support try/except blocks.
      standard-maintenance-scripts-ignore: importlib_resources
